apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  labels:
    app: counter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
      - name: counter-service
        image: 476285196763.dkr.ecr.us-east-1.amazonaws.com/vic-counter-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80