apiVersion: v1
kind: Service
metadata:
  name: vic-counter-service
spec:
  selector:
    app: vic-counter-service-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP