apiVersion: v1
kind: Service
metadata:
  name: vic-counter-service
spec:
  type: NodePort
  selector:
    app: vic-counter-service-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http