name: Run tests

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    - docker_branch
  pull_request:
    branches: [ main ]

jobs:

  terraform:
    name: Testing and Validating Terraform & Kubctl
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Validate failed
      if: ${{ failure() && steps.validate.outputs.failure-reason == 'validate-failed' }}
      run: echo "terraform validate failed"

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan 

    - name: Update Kube Config
      run: aws eks update-kubeconfig --name NEW-vic-eks --region us-east-1

        
    - name: Verify Deployment of the Image to Amazon EKS
      run: |
        echo "kubectl get all"
        kubectl get all

        echo "kubectl get nodes -o wide"
        kubectl get nodes -o wide

        echo "kubectl get pods -o wide"
        kubectl get pods -o wide

        echo "kubectl get svc"
        kubectl get svc
